version: '3.2'

services:

  text-punctuation:
    container_name: text-punctuation-worker
    build: .
    image: lintoai/linto-platform-text-punctuation-worker:latest
    volumes:
      - ${MODEL_PATH}:/home/model-server/model-store/punctuation.mar
      - ${CACHE_PATH}:/home/model-server/.cache/
      - ${LOGS_PATH}:/home/model-server/logs
    ports:
      - target: 8080
        published: 8888
      - target: 8081
        published: 8889
    env_file: .env